In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
X, y = np.arange(10).reshape((5, 2)), range(5) 

In [10]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
list(y)

[0, 1, 2, 3, 4]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [27]:
X_train, '\\', X_test, '\\', y_train, '\\', y_test

(array([[8, 9],
        [6, 7],
        [0, 1]]),
 '\\',
 array([[4, 5],
        [2, 3]]),
 '\\',
 [4, 3, 0],
 '\\',
 [2, 1])

array([[4, 5],
       [2, 3]])